### ISSUE TITLE
Update to d3fc v1.5.0 causes layout of charts to not update correctly

### ISSUE THREAD

**Issue by djmiley** [ScottLogic/d3fc-showcase#291] opened 2015-10-16 13:49 UTC
Works on v1.3.0

This file is probably relevant: https://github.com/ScottLogic/d3fc-showcase/blob/develop/src/assets/js/util/layout.js

Resizing the window does not fix it, zooming and panning still work as expected.

![layout](https://cloud.githubusercontent.com/assets/13115186/10543197/ed55e6c0-7414-11e5-9de1-8c27829cbb31.jpg)

**Comment by jleft** [comment] 2015-10-28 09:14
I'm not sure exactly what this issue is, but I can't reproduce, so I think this is fixed now?

**Comment by djmiley** [comment] 2015-10-28 09:30
I think it was fixed in Arnaud's recent work?

**Comment by Afredon** [comment] 2015-10-28 09:31
Yes, but I spotted new issues with layouts on other browsers now, so still not stable.

**Comment by djmiley** [comment] 2015-10-28 09:32
I think the specific issue is probably fixed in this case.

**Comment by jleft** [comment] 2015-10-28 09:47
Okay, I'll close this - if there is another bug not tracked, then we can open an issue for it.

**Closed by jleft** 2015-10-28 09:47 UTC
Labels: bug

**Comment by jleft** [comment] 2015-10-28 09:52
See #342 for Firefox issue.
